name: projekt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - autopep8=1.6.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_2
  - colorama=0.4.4=pyh9f0ad1d_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.0=py39h06a4308_0
  - matplotlib-base=3.5.0=py39h3ed280b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.1=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.10.1=py39_cu102
  - torchvision=0.11.2=py39_cu102
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==21.4.0
    - backcall==0.2.0
    - bleach==4.1.0
    - cffi==1.15.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.3
    - h5py==3.6.0
    - imageio==2.13.5
    - importrosbag==1.0.3
    - ipykernel==6.6.1
    - ipython==7.31.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - jsonschema==4.3.3
    - jupyter==1.0.0
    - jupyter-client==7.1.0
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclient==0.5.9
    - nbconvert==6.4.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - norse==0.0.7.post1
    - notebook==6.4.6
    - opencv-python==4.5.5.62
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.24
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pygments==2.11.2
    - pyrsistent==0.18.0
    - pyzmq==22.3.0
    - qtconsole==5.2.2
    - qtpy==2.0.0
    - scipy==1.7.3
    - send2trash==1.8.0
    - terminado==0.12.1
    - testpath==0.5.0
    - tonic==1.0.12
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.2
